engines:
  fixme:
    enabled: true
  phpcodesniffer:
    enabled: true
  phpmd:
    enabled: true
ratings:
  paths:
    - "**.php"
    - "**.module"
    - "**.inc"
exclude_paths:
  - config/**/*
  - migrations/**/*
  - spec/**/*
  - src/DefaultServiceProvider.php
  - .codeclimate.yml
  - .gitignore
  - .travis.yml
  - composer.json
  - phinx.yml
  - phpspec.yml
