build:
    environment:
        php:
            version: 7.0
    tests:
        override:
            -
                command: 'bin/phpspec run'
                coverage:
                    file: 'coverage.xml'
                    format: 'php-clover'

filter:
    paths: ["src/*"]
    excluded_paths:
        - "src/Common/ParticleFixes/*"
        - "src/SiteContent/SiteContentServiceProvider.php"
        - "src/DefaultServiceProvider.php"
