build:
    environment:
        php:
            version: 7.0
    tests:
        override:
            -
                command: 'bin/phpspec run'
                coverage:
                    file: 'coverage.xml'
                    format: 'php-clover'

filter:
    paths: ["src/*"]
    excluded_paths:
        - "src/Common/ParticleFixes/*"
        - "src/FileManager/FileManagerServiceProvider.php"
        - "src/SiteContent/SiteContentServiceProvider.php"
        - "src/DefaultServiceProvider.php"

checks:
    php: true
coding_style:
    php:
        spaces:
            before_parentheses:
                closure_definition: true
            around_operators:
                concatenation: true
        upper_lower_casing:
            keywords:
                general: lower
            constants:
                true_false_null: lower
